Приветствую Анатолий!
При выполнении 1 и 2 заданий меня сбила с мысли вводная часть:
"$ odd_to_15 = odd_nums(15)
$ next(odd_to_15)
1
$ next(odd_to_15)
3
...
$ next(odd_to_15)
15
$ next(odd_to_15)
...StopIteration..."
Может я не верно выполнил задания, но в обои решениях ф-ии у меня возвращают
по очереди нечетные целые числа, как того требовалось.
Раскомментирование "next(generator)" выдает в traceback "StopIteration"

Анатолий, Вы можете проверить 2 ДЗ?
https://github.com/VitalyKuzminsky/homework_python_base/pull/2
На портале проверил - ссылка теперь есть, после того, как обратился в техподдержку.
Мы с Вами переписывались в Telegram, что моя ссылка на PR к этому дз на GB не сохранилась.
Может я и сам чего по неопытности напортачил.
Commit к ДЗ 2 на GitHub'е с 03 февраля, домашку нужно было до 05-го сдать.
